quickstart/src/MVCClient/Controllers/StripeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Data.Interfaces;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace MVCClient.Controllers
{
    public class StripeController : Controller
    {
        private readonly IOrder _orderRepository;
        private readonly ShoppingCart _shoppingCart;
        public StripeController(IOrder orderRepositoty, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepositoty;
            _shoppingCart = shoppingCart;
        }
        public IActionResult Index(Orders order)
        {
            return View(order);
        }

        public IActionResult PayWithCard(string stripeEmail, string stripeToken, Orders orders)
        {
            if (User.Identity.IsAuthenticated)
            {
                orders.IdBuyer = User.FindFirstValue("sub");
            }
            _orderRepository.CreateOrder(orders);
            
            var customers = new CustomerService();
            var charges = new ChargeService();

            var customer = customers.Create(new CustomerCreateOptions { 
                Email = stripeEmail,
                Source = stripeToken
            });

            var charge = charges.Create(new ChargeCreateOptions { 
                Amount = (long)orders.OrderTotal,
                Description = "OrderId: " + orders.Id,
                Currency = "vnd",
                Customer = customer.Id,
                ReceiptEmail = stripeEmail
            });

            if(charge.Status == "succeeded")
            {
                string BalanceTransactionId = charge.BalanceTransactionId;
                _orderRepository.Paid(orders);
                _shoppingCart.ClearCard();
                ViewBag.Message = "Thanks for your order";
            }
            return View();
        }

        public IActionResult COD(Orders orders)
        {
            if(User.Identity.IsAuthenticated)
            {
                orders.IdBuyer = User.FindFirstValue("sub");
            }

            _orderRepository.CreateOrder(orders);
            _shoppingCart.ClearCard();

            ViewBag.Message = "Thanks for your order";
            return View();
        }
    }
}

quickstart/src/MVCClient/Views/Stripe/COD.cshtml
@{
    ViewData["Title"] = "COD";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="banner-area relative about-banner" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Your order is processing
                </h1>
                <p class="text-white link-nav"><a asp-controller="Home" asp-action="Index">Home page</a></p>
            </div>
        </div>
    </div>
</section>

<<div class="whole-wrap">
    <div class="container">
        <div class="section-top-border">
            <h3>@ViewBag.Message</h3>
        </div>
    </div>
</div>

quickstart/src/MVCClient/Views/Stripe/Index.cshtml
@using Microsoft.Extensions.Options
@inject IOptions<MVCClient.Data.StripeSettings> Stripe
@model Orders
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="banner-area relative about-banner" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Payment methods
                </h1>
            </div>
        </div>
    </div>
</section>

<div class="whole-wrap">
    <div class="container">
        <div class="section-top-border">
            <div class="row">
                <h3>Customer information</h3>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Phone</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@(Model.FirstName + " " + Model.LastName)</td>
                            <td>@Model.Address</td>
                            <td>@Model.Phone</td>
                            <td>@Model.Email</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="row">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Total</th>
                            <th>Shipping fee</th>
                            <th>Sum total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.OrderTotal Đ</td>
                            <td>25000 Đ</td>
                            <td>@(Model.OrderTotal + 25000)  Đ</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>
                                <form asp-controller="Stripe" asp-action="COD" method="POST">
                                    <button type="submit" class="btn btn-primary">Ship COD</button>
                                    <input hidden asp-for="CreateDate" />
                                    <input hidden asp-for="FirstName" />
                                    <input hidden asp-for="LastName" />
                                    <input hidden asp-for="Email" />
                                    <input hidden asp-for="Address" />
                                    <input hidden asp-for="OrderTotal" />
                                </form>
                            </td>
                            <td>
                                <form asp-controller="Stripe" asp-action="PayWithCard" method="POST">
                                    <input hidden asp-for="CreateDate" />
                                    <input hidden asp-for="FirstName" />
                                    <input hidden asp-for="LastName" />
                                    <input hidden asp-for="Email" />
                                    <input hidden asp-for="Address" />
                                    <input hidden asp-for="OrderTotal" />
                                    <script src="//checkout.stripe.com/v2/checkout.js"
                                            class="stripe-button"
                                            data-key="@Stripe.Value.PublishableKey"
                                            data-locale="auto">
                                    </script>
                                </form>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
    

quickstart/src/MVCClient/Views/Stripe/PayWithCard.cshtml
@{
    ViewData["Title"] = "PayWithCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="banner-area relative about-banner" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Payment succeed
                </h1>
                <p class="text-white link-nav"><a asp-controller="Home" asp-action="Index">Home page</a></p>
            </div>
        </div>
    </div>
</section>

<<div class="whole-wrap">
    <div class="container">
        <div class="section-top-border">
            <h3>@ViewBag.Message</h3>
        </div>
    </div>
</div>