quickstart/src/MVCClient/Controllers/ManageBakeryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCClient.Authorization;
using MVCClient.Models;
using MVCClient.Services;

namespace MVCClient.Controllers
{
    [Authorize(Roles = "Administrators, Managers")]
    public class ManageBakeryController : Controller
    {
        private readonly IBakeryService _service;
        private readonly IAuthorizationService _authorizationService;
        public ManageBakeryController(IBakeryService service, IAuthorizationService authorizationService)
        {
            _service = service;
            _authorizationService = authorizationService;
        }
        public async Task<IActionResult> Index(string TypeSearch, string searchString)
        {
            var menu = await _service.GetCatalog(TypeSearch, searchString);
            var indexViewModel = new IndexViewModel()
            {
                AllBakeryTypes = menu.AllBakeryTypes,
                Bakeries = menu.Bakeries
            };
            return View(indexViewModel);
        }
        public async Task<IActionResult> Detail(int id)
        {
            Bakery bakery = await _service.GetBakery(id);
            return View(bakery);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.listType = await _service.GetTypes();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Bakery bakery, IFormFile Image)
        {
            if (ModelState.IsValid)
            {
                bakery.Status = 1;
                bakery.CreateDate = DateTime.Now;
                await UpdateImage(bakery, Image);

                var isAuthorize = await _authorizationService.AuthorizeAsync(User, bakery, ProductOperations.Create);
                if (!isAuthorize.Succeeded)
                {
                    return Forbid();
                }

                await _service.CreateBakery(bakery);

                return RedirectToAction(nameof(Index));
            }

            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var bakery = await _service.GetBakery(id);
            ViewBag.listType = await _service.GetTypes();

            return View(bakery);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Bakery editBakery, IFormFile Image)
        {
            if (ModelState.IsValid)
            {
                var bakery = await _service.GetBakery(id);

                if (bakery == null)
                {
                    return NotFound();
                }

                var isAuthorize = await _authorizationService.AuthorizeAsync(User, bakery, ProductOperations.Update);
                if (!isAuthorize.Succeeded)
                {
                    return Forbid();
                }

                if(Image != null)
                {
                    await UpdateImage(editBakery, Image);
                }
                else
                {
                    editBakery.Image = bakery.Image;
                }

                await _service.UpdateBakery(id, editBakery);

                return RedirectToAction(nameof(Index));
            }

            return View();
        }
        public async Task<IActionResult> Delete(int id)
        {
            var bakery = await _service.GetBakery(id);

            var isAuthorize = await _authorizationService.AuthorizeAsync(User, bakery, ProductOperations.Update);
            if (!isAuthorize.Succeeded)
            {
                return Forbid();
            }
            bakery.Status = 0;
            await _service.UpdateBakery(id, bakery);

            return RedirectToAction(nameof(Index));
        }

        private async Task UpdateImage(Bakery bakery, IFormFile Image)
        {
            if (Image != null)
            {
                using (var stream = new MemoryStream())
                {
                    await Image.CopyToAsync(stream);
                    bakery.Image = stream.ToArray();
                }
            }
        }
    }
}

quickstart/src/MVCClient/Controllers/ManageBakeryTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCClient.Authorization;
using MVCClient.Models;
using MVCClient.Services;

namespace MVCClient.Controllers
{
    [Authorize(Roles = "Administrators, Managers")]
    public class ManageBakeryTypeController : Controller
    {
        private readonly IBakeryService _service;
        private readonly IAuthorizationService _authorizationService;

        public ManageBakeryTypeController(IBakeryService service, IAuthorizationService authorizationService)
        {
            _service = service;
            _authorizationService = authorizationService;
        }

        public async Task<IActionResult> Index(string searchString)
        {
            IEnumerable<BakeryType> listbakeryType = await _service.GetTypes();
            
            if(!String.IsNullOrEmpty(searchString))
            {
                listbakeryType = listbakeryType.Where(x => x.Name.Contains(searchString)).ToList();
            }
            IndexBakeryTypeViewModel iBTVM = new IndexBakeryTypeViewModel()
            {
                bakeryTypes = listbakeryType,
                searchString = searchString
            };

            return View(iBTVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BakeryType bakeryType)
        {
            if (ModelState.IsValid)
            {
                bakeryType.Status = true;
                //var isAuthorize = await _authorizationService.AuthorizeAsync(User, bakeryType, ProductOperations.Create);
                //if (!isAuthorize.Succeeded)
                //{
                //    return Forbid();
                //}

                await _service.CreateType(bakeryType);

                return RedirectToAction(nameof(Index));
            }

            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var type = await _service.GetType(id);

            return View(type);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BakeryType edittype)
        {
            if (ModelState.IsValid)
            {
                var type = await _service.GetType(id);

                if (type == null)
                {
                    return NotFound();
                }

                var isAuthorize = await _authorizationService.AuthorizeAsync(User, type, ProductOperations.Update);
                if (!isAuthorize.Succeeded)
                {
                    return Forbid();
                }

                await _service.UpdateType(id, edittype);

                return RedirectToAction(nameof(Index));
            }

            return View();
        }
        public async Task<IActionResult> Delete(int id)
        {
            var type = await _service.GetType(id);

            //var isAuthorize = await _authorizationService.AuthorizeAsync(User, type, ProductOperations.Update);
            //if (!isAuthorize.Succeeded)
            //{
            //    return Forbid();
            //}
            type.Status = false;
            await _service.UpdateType(id, type);

            return RedirectToAction(nameof(Index));
        }
    }
}

quickstart/src/MVCClient/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCClient.Authorization;
using MVCClient.Models;
using MVCClient.Services;

namespace MVCClient.Controllers
{
    [AllowAnonymous]
    public class MenuController : Controller
    {
        private readonly IBakeryService _service;
        private readonly IAuthorizationService _authorizationService;
        public MenuController(IBakeryService service, IAuthorizationService authorizationService)
        {
            _service = service;
            _authorizationService = authorizationService;
        }
        
        public async Task<IActionResult> Index(string bakeryType, string searchString)
        {
            var menu = await _service.GetCatalog(bakeryType, searchString);

            var indexViewModel = new IndexViewModel()
            {
                AllBakeryTypes = menu.AllBakeryTypes,
                Bakeries = menu.Bakeries,
                BakeriesSale = menu.Bakeries.Where(x => x.Discount > 0).ToList(),
                BakeriesNew = menu.Bakeries.Where(x => (DateTime.Now - x.CreateDate).Days < 30).ToList()
            };
            return View(indexViewModel);
        }
        public async Task<IActionResult> Detail(int id)
        {
            Bakery bakery = await _service.GetBakery(id);
            return View(bakery);
        }

    }
}

quickstart/src/MVCClient/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using MVCClient.Models;
using MVCClient.Services;

namespace MVCClient.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IBakeryService _service;
        private readonly ShoppingCart _shoppingcart;
        public ShoppingCartController(IBakeryService service, ShoppingCart shoppingCart)
        {
            _service = service;
            _shoppingcart = shoppingCart;
        }
        public ViewResult Index()
        {
            var items = _shoppingcart.GetShoppingCartItem();
            _shoppingcart.ShoppingCartItem = items;

            var scVM = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingcart,
                ShoppingCartTotal = _shoppingcart.GetShoppingCartTotal()
            };

            return View(scVM);
        }

        public async Task<JsonResult> AddToShoppingCart(int id, int amount)
        {
            try
            {
                Bakery selectedBakery = await _service.GetBakery(id);
                if (selectedBakery != null)
                {
                    _shoppingcart.AddToCart(selectedBakery, amount);
                }
                return Json(new
                {
                    status = true
                });
            }
            catch
            {
                return Json(new
                {
                    status = false
                });
            }
        }

        public async Task<RedirectToActionResult> RemoveFromShoppingCart(int id)
        {
            var selectedBakery = await _service.GetBakery(id);
            if (selectedBakery != null)
            {
                _shoppingcart.RemoveFromCart(selectedBakery);
            }

            return RedirectToAction("Index");
        }
    }
}

quickstart/src/MVCClient/Views/Shared/_Admin.cshtml
@if (User.IsInRole("Managers") || User.IsInRole("Administrators"))
{
    <a href="#">Manage</a>
    <ul>
        <li><a asp-action="Index" asp-controller="ManageBakery">Bakeries</a></li>
        <li><a asp-action="Index" asp-controller="ManageBakeryType">Bakery types</a></li>
        <li><a asp-action="Index" asp-controller="ManageOrder">Orders</a></li>
        @if (User.IsInRole("Administrators"))
        {
            <li><a href='@string.Format("http://localhost:5000/manageacount?id={0}", User.FindFirstValue("sub"))'>Accounts</a></li>
        }
    </ul>
}

quickstart/src/MVCClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCClient</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link rel="stylesheet" href="~/css/jquery-ui.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>

<body>
    <header id="header">
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <a asp-controller="Home" asp-action="Index"><img src="~/img/logo.png" alt="" title="" /></a>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li class="menu-has-children"><partial name="_Admin" /></li>
                        <li class="menu-active"><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Menu" asp-action="Index">Menu</a></li>
                        <li><a asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                        <li><a asp-controller="ShoppingCart" asp-action="Index">Cart</a></li>
                        <li class="menu-has-children"><partial name="_LoginPartial" /></li>
                        @*<li class="menu-has-children">
            <a href="">Blog</a>
            <ul>
                <li><a href="blog-home.html">Blog Home</a></li>
                <li><a href="blog-single.html">Blog Single</a></li>
                <li class="menu-has-children">
                    <a href="">Level 2</a>
                    <ul>
                        <li><a href="#">Item One</a></li>
                        <li><a href="#">Item Two</a></li>
                    </ul>
                </li>
            </ul>
        </li>*@
                    </ul>
                </nav><!-- #nav-menu-container -->
            </div>
        </div>
    </header><!-- #header -->

    @RenderBody()

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Us</h6>
                        <p>
                            If you own an Iphone, you’ve probably already worked out how much fun it is to use it to watch movies-it has that.
                        </p>
                    </div>
                </div>
                <div class="col-lg-5  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>Stay update with our latest</p>
                        <div class="" id="mc_embed_signup">
                            <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">
                                <input class="form-control" name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address'" required="" type="email">
                                <button class="click-btn"><i class="lnr lnr-arrow-right" aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                </div>
                                <div class="info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                    <div class="single-footer-widget">
                        <h6>Follow Us</h6>
                        <p>Let us be social</p>
                        <div class="footer-social d-flex align-items-center">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <p class="footer-text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>

    </footer>
    <!-- End footer Area -->

    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="~/js/easing.min.js"></script>
    <script src="~/js/hoverIntent.js"></script>
    <script src="~/js/superfish.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>